{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "검색어를 입력하세요:  게이밍 마웃\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\n",
      "\"lastBuildDate\": \"Sun, 10 May 2020 12:53:38 +0900\",\n",
      "\"total\": 24450,\n",
      "\"start\": 1,\n",
      "\"display\": 10,\n",
      "\"items\": [\n",
      "{\n",
      "\"title\": \"<b>게이밍 마우스</b> 벤큐 조위 EC2 사용해 본 <b>후기</b>!\",\n",
      "\"link\": \"https:\\/\\/blog.naver.com\\/doem011?Redirect=Log&logNo=221950116824\",\n",
      "\"description\": \"그래서 이번에는 FPS 게임을 위한 최적의 그립감으로 오른손잡이 전용으로 출시된 벤큐 조위 EC2 <b>게이밍 마우스</b>를 구매해서 직접 사용해 본 <b>후기</b>를 써 내려가 보려고 합니다. EC SERIES 최고의 그립감으로... \",\n",
      "\"bloggername\": \"아빠는 간다\",\n",
      "\"bloggerlink\": \"https://blog.naver.com/doem011\",\n",
      "\"postdate\": \"20200507\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"블루투스와 무선 다 되는 로지텍 G604 <b>게이밍 마우스 후기</b>\",\n",
      "\"link\": \"https:\\/\\/blog.naver.com\\/soary81?Redirect=Log&logNo=221888899401\",\n",
      "\"description\": \"그렇기에 단순히 <b>게이밍 마우스</b>로만 생각하기 보다는 게임용이지만 작업용까지 모두 소화할 수 있는 그런 제품이라고 볼 수 있었고, 실제로 약 2주 정도 게임과 일을 할 때를 가리지 않고 써 본 결과 '이건... \",\n",
      "\"bloggername\": \"소라윙즈의 소소한 IT/게임 리뷰\",\n",
      "\"bloggerlink\": \"https://blog.naver.com/soary81\",\n",
      "\"postdate\": \"20200406\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"다얼유 EM901 무선 <b>게이밍 마우스</b> 사용 <b>후기</b>\",\n",
      "\"link\": \"https:\\/\\/blog.naver.com\\/winsweet?Redirect=Log&logNo=221579181760\",\n",
      "\"description\": \"대부분 높은 가격대를 유지하고 있지만, 이젠 대중성을 갖춘 합리적인 가격대로 형성된 #무선<b>게이밍마우스</b> 들이 늘어가고 있습니다. ▲ #다얼유 브랜드는 중국에서 단일 모델 매출 1위를 기록할 정도로... \",\n",
      "\"bloggername\": \"PLAY IT : enow.co.kr\",\n",
      "\"bloggerlink\": \"https://blog.naver.com/winsweet\",\n",
      "\"postdate\": \"20190706\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"<b>게이밍 마우스</b> EC2 으뜸이다!\",\n",
      "\"link\": \"https:\\/\\/blog.naver.com\\/jwlove4?Redirect=Log&logNo=221848728646\",\n",
      "\"description\": \"싶어 게이밍 마우스를 구매하게 되었어요. 여러 가지 제품을 구경하다가 심플하게 생기고 후기가... 이렇게 제가 구매한 벤큐 조위 EC2 제품의 <b>게이밍 마우스 후기</b>를 적어봤는데요. 자주 게임을 즐기시거나... \",\n",
      "\"bloggername\": \"파크의 IT 이야기\",\n",
      "\"bloggerlink\": \"https://blog.naver.com/jwlove4\",\n",
      "\"postdate\": \"20200311\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"로지텍 G102 PRODIGY <b>게이밍 마우스</b> 사용<b>후기</b>\",\n",
      "\"link\": \"https:\\/\\/blog.naver.com\\/mkl86?Redirect=Log&logNo=221574009686\",\n",
      "\"description\": \"그럼 마지막으로 장패드를 제대로 보여드리면서 <b>후기</b> 마치도록 하겠습니다. #로지텍, #<b>마우스</b>, #<b>게이밍</b>, #폴링레이트, #LED, #유선, #<b>게이밍</b>, #USB PS4 성인용 RPG 한계돌파 캐슬판처즈 한정판 특전 장패드(6명... \",\n",
      "\"bloggername\": \"초특급 변태의 일기장\",\n",
      "\"bloggerlink\": \"https://blog.naver.com/mkl86\",\n",
      "\"postdate\": \"20190630\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"가벼운 <b>마우스</b> 레이저 바이퍼 미니 <b>게이밍</b> <b>후기</b>\",\n",
      "\"link\": \"https:\\/\\/blog.naver.com\\/kas2724?Redirect=Log&logNo=221925577361\",\n",
      "\"description\": \"보통 경량을 위한 <b>게이밍 마우스</b>의 경우 타공 설계를 적용한 경우가 많지만, 문제는 이물질이나 내구력에 약하다는 단점이 있다. 물론 최근에는 개선된 제품들이 많이 출시되었으나, 구조적 무결성과 가벼운... \",\n",
      "\"bloggername\": \"Qwerty IT\",\n",
      "\"bloggerlink\": \"https://blog.naver.com/kas2724\",\n",
      "\"postdate\": \"20200423\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"로지텍 G304 무선 <b>게이밍 마우스</b> 사용<b>후기</b> (G HUB 드라이버... \",\n",
      "\"link\": \"https:\\/\\/blog.naver.com\\/nangamssa?Redirect=Log&logNo=221906818394\",\n",
      "\"description\": \"얘기였나 봅니다 ㅎㅎ 로지텍 G304 모델을 써보니 전혀 불편함을 느낄 수가 없네요~ 다음엔 무선 키보드를 사야 하나..?? 이상! 로지텍 G304 무선 <b>게이밍 마우스</b> 사용<b>후기</b> (G HUB 드라이버 다운로드) 포스팅 끝~\",\n",
      "\"bloggername\": \"동그란 블로그\",\n",
      "\"bloggerlink\": \"https://blog.naver.com/nangamssa\",\n",
      "\"postdate\": \"20200413\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"<b>게이밍 마우스</b> ::에이픽스 GM001 가성비<b>마우스 후기</b>\",\n",
      "\"link\": \"https:\\/\\/blog.naver.com\\/kittyhwang?Redirect=Log&logNo=221822074010\",\n",
      "\"description\": \"저는 게임을 많이 하지는 않지만 사진작업을 하는데 있어서 <b>마우스</b>를 쥐고 있는 손이 아파지만 오래 못해서 이부분이 가장 중요했어요 근데 많은 <b>후기</b>들을 살펴보니 <b>게이밍 마우스</b>가 그립감도 좋고 감도도... \",\n",
      "\"bloggername\": \"검소한여인의 블로그♥️\",\n",
      "\"bloggerlink\": \"https://blog.naver.com/kittyhwang\",\n",
      "\"postdate\": \"20200224\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"로지텍 G502 무선 <b>게이밍 마우스</b> &amp; 파워플레이 배그 <b>후기</b>\",\n",
      "\"link\": \"https:\\/\\/blog.naver.com\\/supapa13?Redirect=Log&logNo=221782268914\",\n",
      "\"description\": \"로지텍 G502 무선 <b>게이밍 마우스</b> &amp; 파워플레이 배그 <b>후기</b> PC 게임을 하면서 유선을 굳이 선호하는 사람은 없을 겁니다. 무선으로도 똑같은 아니 그 이상의 성능을 뽑아낼 수 있다면 말이죠. 물론 단순히 선이... \",\n",
      "\"bloggername\": \"세수하면이병헌 IT, 육아\",\n",
      "\"bloggerlink\": \"https://blog.naver.com/supapa13\",\n",
      "\"postdate\": \"20200123\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"가성비 좋은 <b>게이밍마우스</b> GM003 사용 <b>후기</b>\",\n",
      "\"link\": \"https:\\/\\/blog.naver.com\\/obama8775?Redirect=Log&logNo=221729673509\",\n",
      "\"description\": \"요즘에는 <b>게이밍마우스</b>로 다양한 제품들이 많이 나오고 있지만 성능이 좋지만 가격이 저렴한 제품을... 고스펙 <b>마우스</b>에 있는 옵션들이 있는 가성비 좋은 GM003 사용 <b>후기</b>를 써보려고 합니다. <b>마우스</b>는 쓰면... \",\n",
      "\"bloggername\": \"선비의 엣헴블로그\",\n",
      "\"bloggerlink\": \"https://blog.naver.com/obama8775\",\n",
      "\"postdate\": \"20191207\"\n",
      "\n",
      "}\n",
      "]\n",
      "}\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# 네이버 블로그 검색 API 이용\n",
    "# 검색한 제품의 후기 블로그 출력\n",
    "\n",
    "import os\n",
    "import sys\n",
    "import urllib.request\n",
    "from urllib.parse import urlparse\n",
    "client_id = \"MxAYTCOsbligdEvHngib\"\n",
    "client_secret = \"3iRpVzgyLb\"\n",
    "\n",
    "text = input(\"검색어를 입력하세요: \")\n",
    "new_text = (text + \"후기\")\n",
    "encText = urllib.parse.quote(new_text)\n",
    "\n",
    "url = \"https://openapi.naver.com/v1/search/blog?query=\" + encText # json 결과\n",
    "\n",
    "request = urllib.request.Request(url)\n",
    "request.add_header(\"X-Naver-Client-Id\",client_id)\n",
    "request.add_header(\"X-Naver-Client-Secret\",client_secret)\n",
    "response = urllib.request.urlopen(request)\n",
    "rescode = response.getcode()\n",
    "\n",
    "if(rescode==200):\n",
    "    response_body = response.read()\n",
    "    print(response_body.decode('utf-8'))\n",
    "else:\n",
    "    print(\"Error Code:\" + rescode)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "검색어를 입력하세요:  게이밍 마우스\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\n",
      "\"lastBuildDate\": \"Sun, 26 Apr 2020 13:52:07 +0900\",\n",
      "\"total\": 352250,\n",
      "\"start\": 1,\n",
      "\"display\": 10,\n",
      "\"items\": [\n",
      "{\n",
      "\"title\": \"로지텍G G102 Prodigy\",\n",
      "\"link\": \"https://search.shopping.naver.com/gate.nhn?id=10565213662\",\n",
      "\"image\": \"https://shopping-phinf.pstatic.net/main_1056521/10565213662.20191028105407.jpg\",\n",
      "\"lprice\": \"19300\",\n",
      "\"hprice\": \"445000\",\n",
      "\"mallName\": \"네이버\",\n",
      "\"productId\": \"10565213662\",\n",
      "\"productType\": \"1\",\n",
      "\"brand\": \"로지텍G\",\n",
      "\"maker\": \"로지텍\",\n",
      "\"category1\": \"디지털/가전\",\n",
      "\"category2\": \"주변기기\",\n",
      "\"category3\": \"마우스\",\n",
      "\"category4\": \"유선마우스\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"COX CM50 RGB <b>게이밍 마우스</b>\",\n",
      "\"link\": \"https://search.shopping.naver.com/gate.nhn?id=15220137606\",\n",
      "\"image\": \"https://shopping-phinf.pstatic.net/main_1522013/15220137606.20180903121804.jpg\",\n",
      "\"lprice\": \"14800\",\n",
      "\"hprice\": \"29220\",\n",
      "\"mallName\": \"네이버\",\n",
      "\"productId\": \"15220137606\",\n",
      "\"productType\": \"1\",\n",
      "\"brand\": \"COX\",\n",
      "\"maker\": \"\",\n",
      "\"category1\": \"디지털/가전\",\n",
      "\"category2\": \"주변기기\",\n",
      "\"category3\": \"마우스\",\n",
      "\"category4\": \"유선마우스\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"COX CM60 TARGET RGB <b>게이밍 마우스</b>\",\n",
      "\"link\": \"https://search.shopping.naver.com/gate.nhn?id=13801105380\",\n",
      "\"image\": \"https://shopping-phinf.pstatic.net/main_1380110/13801105380.20191231163623.jpg\",\n",
      "\"lprice\": \"27500\",\n",
      "\"hprice\": \"47270\",\n",
      "\"mallName\": \"네이버\",\n",
      "\"productId\": \"13801105380\",\n",
      "\"productType\": \"1\",\n",
      "\"brand\": \"COX\",\n",
      "\"maker\": \"\",\n",
      "\"category1\": \"디지털/가전\",\n",
      "\"category2\": \"주변기기\",\n",
      "\"category3\": \"마우스\",\n",
      "\"category4\": \"유선마우스\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"앱코 해커 A660 3325 프로페셔널 <b>게이밍 마우스</b>\",\n",
      "\"link\": \"https://search.shopping.naver.com/gate.nhn?id=12098611950\",\n",
      "\"image\": \"https://shopping-phinf.pstatic.net/main_1209861/12098611950.20170821173400.jpg\",\n",
      "\"lprice\": \"22900\",\n",
      "\"hprice\": \"45000\",\n",
      "\"mallName\": \"네이버\",\n",
      "\"productId\": \"12098611950\",\n",
      "\"productType\": \"1\",\n",
      "\"brand\": \"해커\",\n",
      "\"maker\": \"앱코\",\n",
      "\"category1\": \"디지털/가전\",\n",
      "\"category2\": \"주변기기\",\n",
      "\"category3\": \"마우스\",\n",
      "\"category4\": \"유선마우스\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"로지텍G G PRO HERO <b>게이밍 마우스</b>\",\n",
      "\"link\": \"https://search.shopping.naver.com/gate.nhn?id=15119702254\",\n",
      "\"image\": \"https://shopping-phinf.pstatic.net/main_1511970/15119702254.20181206154631.jpg\",\n",
      "\"lprice\": \"63020\",\n",
      "\"hprice\": \"163800\",\n",
      "\"mallName\": \"네이버\",\n",
      "\"productId\": \"15119702254\",\n",
      "\"productType\": \"1\",\n",
      "\"brand\": \"로지텍G\",\n",
      "\"maker\": \"로지텍\",\n",
      "\"category1\": \"디지털/가전\",\n",
      "\"category2\": \"주변기기\",\n",
      "\"category3\": \"마우스\",\n",
      "\"category4\": \"유선마우스\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"앱코 해커 A200 3050 RGB <b>게이밍 마우스</b>\",\n",
      "\"link\": \"https://search.shopping.naver.com/gate.nhn?id=19559178604\",\n",
      "\"image\": \"https://shopping-phinf.pstatic.net/main_1955917/19559178604.20191231182907.jpg\",\n",
      "\"lprice\": \"17900\",\n",
      "\"hprice\": \"24940\",\n",
      "\"mallName\": \"네이버\",\n",
      "\"productId\": \"19559178604\",\n",
      "\"productType\": \"1\",\n",
      "\"brand\": \"해커\",\n",
      "\"maker\": \"앱코\",\n",
      "\"category1\": \"디지털/가전\",\n",
      "\"category2\": \"주변기기\",\n",
      "\"category3\": \"마우스\",\n",
      "\"category4\": \"유선마우스\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"앱코 HACKER A530 3325 RGB <b>게이밍 마우스</b>\",\n",
      "\"link\": \"https://search.shopping.naver.com/gate.nhn?id=15004922308\",\n",
      "\"image\": \"https://shopping-phinf.pstatic.net/main_1500492/15004922308.20180809103331.jpg\",\n",
      "\"lprice\": \"21500\",\n",
      "\"hprice\": \"45510\",\n",
      "\"mallName\": \"네이버\",\n",
      "\"productId\": \"15004922308\",\n",
      "\"productType\": \"1\",\n",
      "\"brand\": \"앱코\",\n",
      "\"maker\": \"앱코\",\n",
      "\"category1\": \"디지털/가전\",\n",
      "\"category2\": \"주변기기\",\n",
      "\"category3\": \"마우스\",\n",
      "\"category4\": \"유선마우스\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"앱코 해커 A700 하이엔드 <b>게이밍 마우스</b>\",\n",
      "\"link\": \"https://search.shopping.naver.com/gate.nhn?id=9985003669\",\n",
      "\"image\": \"https://shopping-phinf.pstatic.net/main_9985003/9985003669.20160630142814.jpg\",\n",
      "\"lprice\": \"38900\",\n",
      "\"hprice\": \"846720\",\n",
      "\"mallName\": \"네이버\",\n",
      "\"productId\": \"9985003669\",\n",
      "\"productType\": \"1\",\n",
      "\"brand\": \"해커\",\n",
      "\"maker\": \"앱코\",\n",
      "\"category1\": \"디지털/가전\",\n",
      "\"category2\": \"주변기기\",\n",
      "\"category3\": \"마우스\",\n",
      "\"category4\": \"유선마우스\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"앱코 해커 A660 3360 하이엔드 <b>게이밍 마우스</b>\",\n",
      "\"link\": \"https://search.shopping.naver.com/gate.nhn?id=12140397248\",\n",
      "\"image\": \"https://shopping-phinf.pstatic.net/main_1214039/12140397248.20170828164834.jpg\",\n",
      "\"lprice\": \"33500\",\n",
      "\"hprice\": \"68780\",\n",
      "\"mallName\": \"네이버\",\n",
      "\"productId\": \"12140397248\",\n",
      "\"productType\": \"1\",\n",
      "\"brand\": \"해커\",\n",
      "\"maker\": \"앱코\",\n",
      "\"category1\": \"디지털/가전\",\n",
      "\"category2\": \"주변기기\",\n",
      "\"category3\": \"마우스\",\n",
      "\"category4\": \"유선마우스\"\n",
      "\n",
      "},\n",
      "{\n",
      "\"title\": \"COX CM90W 유무선 RGB <b>게이밍 마우스</b>\",\n",
      "\"link\": \"https://search.shopping.naver.com/gate.nhn?id=19460101406\",\n",
      "\"image\": \"https://shopping-phinf.pstatic.net/main_1946010/19460101406.20190524175534.jpg\",\n",
      "\"lprice\": \"31470\",\n",
      "\"hprice\": \"62150\",\n",
      "\"mallName\": \"네이버\",\n",
      "\"productId\": \"19460101406\",\n",
      "\"productType\": \"1\",\n",
      "\"brand\": \"COX\",\n",
      "\"maker\": \"\",\n",
      "\"category1\": \"디지털/가전\",\n",
      "\"category2\": \"주변기기\",\n",
      "\"category3\": \"마우스\",\n",
      "\"category4\": \"무선마우스\"\n",
      "\n",
      "}\n",
      "]\n",
      "}\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# 네이버 쇼핑 검색 API 이용\n",
    "# 검색어에 따른 쇼핑 제품 결과 출력\n",
    "\n",
    "import os\n",
    "import sys\n",
    "import urllib.request\n",
    "client_id = \"MxAYTCOsbligdEvHngib\"\n",
    "client_secret = \"3iRpVzgyLb\"\n",
    "\n",
    "text = input(\"검색어를 입력하세요: \")\n",
    "encText = urllib.parse.quote(text)\n",
    "\n",
    "url = \"https://openapi.naver.com/v1/search/shop?query=\" + encText # json 결과\n",
    "\n",
    "request = urllib.request.Request(url)\n",
    "request.add_header(\"X-Naver-Client-Id\",client_id)\n",
    "request.add_header(\"X-Naver-Client-Secret\",client_secret)\n",
    "response = urllib.request.urlopen(request)\n",
    "rescode = response.getcode()\n",
    "\n",
    "if(rescode==200):\n",
    "    response_body = response.read()\n",
    "    print(response_body.decode('utf-8'))\n",
    "else:\n",
    "    print(\"Error Code:\" + rescode)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "검색어를 입력하세요:  겡밍 마우스\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\n",
      "\"errata\": \"게이밍 마우스\"\n",
      "}\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# 네이버 오타변환 검색 API 이용\n",
    "# 검색어에 오타가 있을 경우, \"errata\" 값에 수정된 값 출력\n",
    "# 오타가 없을 경우, 빈 문자열 출력\n",
    "\n",
    "import os\n",
    "import sys\n",
    "import urllib.request\n",
    "client_id = \"MxAYTCOsbligdEvHngib\"\n",
    "client_secret = \"3iRpVzgyLb\"\n",
    "\n",
    "text = input(\"검색어를 입력하세요: \")\n",
    "encText = urllib.parse.quote(text)\n",
    "\n",
    "url = \"https://openapi.naver.com/v1/search/errata?query=\" + encText # json 결과\n",
    "\n",
    "request = urllib.request.Request(url)\n",
    "request.add_header(\"X-Naver-Client-Id\",client_id)\n",
    "request.add_header(\"X-Naver-Client-Secret\",client_secret)\n",
    "response = urllib.request.urlopen(request)\n",
    "rescode = response.getcode()\n",
    "\n",
    "if(rescode==200):\n",
    "    response_body = response.read()\n",
    "    print(response_body.decode('utf-8'))\n",
    "else:\n",
    "    print(\"Error Code:\" + rescode)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "검색할 단어를 입력하세요:  게이밍 마우스\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "------------------Crawling Result-----------------\n",
      "게이밍 마우스 벤큐 조위 EC2 사용해 본 후기!\n",
      "https://blog.naver.com/doem011?Redirect=Log&logNo=221950116824\n",
      "\n",
      "블루투스와 무선 다 되는 로지텍 G604 게이밍 마우스 후기\n",
      "https://blog.naver.com/soary81?Redirect=Log&logNo=221888899401\n",
      "\n",
      "다얼유 EM901 무선 게이밍 마우스 사용 후기\n",
      "https://blog.naver.com/winsweet?Redirect=Log&logNo=221579181760\n",
      "\n",
      "로지텍 G102 PRODIGY 게이밍 마우스 사용후기\n",
      "https://blog.naver.com/mkl86?Redirect=Log&logNo=221574009686\n",
      "\n",
      "게이밍 마우스 EC2 으뜸이다!\n",
      "https://blog.naver.com/jwlove4?Redirect=Log&logNo=221848728646\n",
      "\n",
      "가벼운 마우스 레이저 바이퍼 미니 게이밍 후기\n",
      "https://blog.naver.com/kas2724?Redirect=Log&logNo=221925577361\n",
      "\n",
      "로지텍 G304 무선 게이밍 마우스 사용후기 (G HUB 드라이버...\n",
      "https://blog.naver.com/nangamssa?Redirect=Log&logNo=221906818394\n",
      "\n",
      "게이밍 마우스 ::에이픽스 GM001 가성비마우스 후기\n",
      "https://blog.naver.com/kittyhwang?Redirect=Log&logNo=221822074010\n",
      "\n",
      "로지텍 G502 무선 게이밍 마우스 &amp; 파워플레이 배그 후기\n",
      "https://blog.naver.com/supapa13?Redirect=Log&logNo=221782268914\n",
      "\n",
      "가성비 좋은 게이밍마우스 GM003 사용 후기\n",
      "https://blog.naver.com/obama8775?Redirect=Log&logNo=221729673509\n",
      "\n",
      "--------------------------------------------------\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import sys\n",
    "import urllib.request\n",
    "import requests\n",
    "import re\n",
    "\n",
    "client_id = \"MxAYTCOsbligdEvHngib\"\n",
    "client_secret = \"3iRpVzgyLb\"\n",
    "\n",
    "searchWord = input(\"검색할 단어를 입력하세요: \")\n",
    "newSearchWord = searchWord + '후기'\n",
    "\n",
    "encText = urllib.parse.quote(newSearchWord)\n",
    "url = 'https://openapi.naver.com/v1/search/blog?query=' + encText\n",
    "\n",
    "request = urllib.request.Request(url)\n",
    "request.add_header(\"X-Naver-Client-Id\", client_id)\n",
    "request.add_header(\"X-Naver-Client-Secret\", client_secret)\n",
    "\n",
    "response = urllib.request.urlopen(request)\n",
    "responseCode = response.getcode()\n",
    "if responseCode == 200:\n",
    "    print('------------------Crawling Result-----------------')\n",
    "    responseBodys = response.readlines()\n",
    "    for responseBody in responseBodys:\n",
    "        if responseBody.startswith(b'\"title\"'): # title만 추출\n",
    "            titleResult = responseBody.decode('utf-8') # 자연어로 변환\n",
    "            newTitleResult = str(titleResult) # byte - string 변환\n",
    "            \n",
    "            # 불필요한 문자열, 태그 제거          \n",
    "            titleResultResponse = re.sub('<.+?>', '', newTitleResult, 0, re.I|re.S)\n",
    "            titleResultResponse = re.sub('\"title\":', '', titleResultResponse, 0, re.I|re.S)\n",
    "            titleResultResponse = re.sub(',', '', titleResultResponse)\n",
    "            titleResultResponse = re.sub('\"', '', titleResultResponse)\n",
    "            \n",
    "            print(titleResultResponse.strip()) # 출력\n",
    "        elif responseBody.startswith(b'\"link\"'): # link만 추출\n",
    "            linkResult = responseBody.decode('utf-8') # 자연어로 변환\n",
    "            newLinkResult = str(linkResult) # byte - string 변환\n",
    "            \n",
    "            # 불필요한 문자열, 태그 제거\n",
    "            linkResultResponse = re.sub('<.+?>', '', newLinkResult, 0, re.I|re.S)\n",
    "            linkResultResponse = re.sub('\"link\":', '', linkResultResponse, 0, re.I|re.S)\n",
    "            linkResultResponse = re.sub(',', '', linkResultResponse)\n",
    "            linkResultResponse = re.sub('\"', '', linkResultResponse)\n",
    "            linkResultResponse = re.sub('\\\\\\\\', '', linkResultResponse)\n",
    "            \n",
    "            print(linkResultResponse.strip())\n",
    "            print()\n",
    "        else:\n",
    "            continue\n",
    "            \n",
    "    print('--------------------------------------------------')\n",
    "else:\n",
    "    print('Error Code:' + responseCode)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
